import com.itextpdf.text.BadElementException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.Statement;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Font;
import java.io.IOException;
import java.net.URL;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author beckyponce
 */
public class addmin extends javax.swing.JPanel {
    conectar con = new conectar();
    Connection reg = con.conexion();
    String nom,cel,equipo,equip,marca,modelo,sn,eliminador,notas,contraseña,emp,folio,en;
    int op;
    DateTimeFormatter time;
    /**
     * Creates new form addmin
     */
    public addmin() {
        initComponents();
    }
    public void guardarDatos(){
        nom = jTextField1.getText().toUpperCase();
        cel = jTextField2.getText().toUpperCase();
        equipo = jComboBox1.getSelectedItem().toString().toUpperCase();
        if(equipo.equals("Otro")){
            equip = JOptionPane.showInputDialog(null,"Ingrese el tipo de equipo:").toUpperCase();
        }else{
            equip = jComboBox1.getSelectedItem().toString().toUpperCase();
        }
        marca = jTextField3.getText().toUpperCase();
        modelo = jTextField4.getText().toUpperCase();
        if(jRadioButton1.isSelected()){
            eliminador = "SI";
        }else if(jRadioButton2.isSelected()){
            eliminador = "NO";
        }
        sn = jTextField5.getText().toUpperCase();
        notas = jTextArea1.getText().toUpperCase();
        time = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm");
        if(nom.isEmpty()||cel.isEmpty()||marca.isEmpty()||modelo.isEmpty()||sn.isEmpty()){
            //JOptionPane.showMessageDialog(null,"Complete los campos obligatorios porfavor:)");
        }else{
            emp=JOptionPane.showInputDialog(null,"¿Quien esta dando de alta el equipo?").toUpperCase();
            if(equip.equals("LAPTOP")||equip.equals("CPU")||equip.equals("ALL IN ONE")||equip.equals("TABLET")||equip.equals("CELULAR")||equip.equals("OTRO")){
                op=JOptionPane.showConfirmDialog(null,"¿Tiene contraseña el equipo?","",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                //emp=JOptionPane.showInputDialog(null,"¿Quien esta dando de alta el equipo?").toUpperCase();
                if(op==0){
                    contraseña=JOptionPane.showInputDialog(null,"Ingrese la contraseña del equipo: ");
                }else{
                    contraseña="NO TIENE";
                }
            }else{
                contraseña="NO APLICA";
            }
        }
    }
    public void limpiar(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextArea1.setText("");
        jComboBox1.setSelectedItem("Laptop");
        jRadioButton2.setSelected(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 416));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triangulo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Nombre del cliente:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Celular o Telefono:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Equipo:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "CPU", "All in one", "Impresora", "Toner", "Cartucho de tinta", "Tablet", "Celular", "Otro" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Marca:");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Modelo:");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("Eliminador:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Si");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("No");
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("Notas:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("S/N:");

        jButton1.setText("Guardar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("*");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("*");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("*");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("*");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 51));
        jLabel14.setText("*");

        jButton2.setText("Generar Archivo");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton1))
                            .addComponent(jTextField2)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5)
                            .addComponent(jTextField1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        guardarDatos();
        if(nom.equals("")||cel.equals("")||marca.equals("")||modelo.equals("")||sn.equals("")){
            JOptionPane.showMessageDialog(null,"Complete los campos obligatorios porfavor:)");
        }else{
            /*System.out.println("Checando... \nNombre Cliente: "+nom+"\nTelefono: "+cel+"\nEquipo: "+equipo+"\nMarca: "+marca+
            "\nModelo: "+modelo+"\nSN: "+sn+"\nEliminador: "+eliminador+"\nContraseña: "+contraseña
            +"\nNotas: "+notas+"\nEmpleado: "+emp+"\nFecha y hora: "+time.format(LocalDateTime.now()));*/
            String sql="INSERT INTO sist (NOMBRE,TELEFONO,EQUIPO,MARCA,MODELO,SN,ELIMINADOR,CONTRASEÑA,NOTAS,EMPLEADO,FECHA) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
            try {
                PreparedStatement ps= reg.prepareStatement(sql);
                ps.setString(1, nom);
                ps.setString(2, cel);
                ps.setString(3, equip);
                ps.setString(4, marca);
                ps.setString(5, modelo);
                ps.setString(6, sn);
                ps.setString(7, eliminador);
                ps.setString(8, contraseña);
                ps.setString(9, notas);
                ps.setString(10, emp);
                ps.setString(11, time.format(LocalDateTime.now()));
                ps.executeUpdate();                
                //System.out.println(nom+"\n"+cel+"\n"+equip+"\n"+marca+"\n"+modelo+"\n"+sn+"\n"+eliminador+"\n"+notas+"\n"+contraseña);
                JOptionPane.showMessageDialog(null,"Guardado correctamente:)");
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Ha ocurrido un error:(\n"+ex);
                Logger.getLogger(addmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals("")||jTextField2.getText().equals("")||jTextField3.getText().equals("")||jTextField4.getText().equals("")||jTextField5.getText().equals("")){
            JOptionPane.showMessageDialog(null,"No se puede generar reporte con campos vacios:)");
        }else{
            Document documento = new Document();
            try{
                try{
                    Statement sentencia1=reg.createStatement();
                    ResultSet rs1= sentencia1.executeQuery("SELECT MAX(FOLIO) FROM sist");
                    while(rs1.next()){
                        folio = rs1.getString(1);
                    }
                    //System.out.println(folio);
                }catch(SQLException ex){
                    JOptionPane.showMessageDialog(null,"Algo salio mal:(\n"+ex);
                    Logger.getLogger(addmin.class.getName()).log(Level.SEVERE, null, ex);
                }
                String ruta = System.getProperty("user.home");
                PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/"+folio+" "+equipo+".pdf"));
                String h1 = "header.png";
                String f1 = "firma.png";
                URL h1url = this.getClass().getResource(h1);
                URL f1url = this.getClass().getResource(f1);
                Image header = Image.getInstance(h1url);
                header.scaleToFit(500,170);
                header.setAlignment(Chunk.ALIGN_CENTER);
                Image firma = Image.getInstance(f1url);
                firma.scaleToFit(500,182);
                firma.setAlignment(Chunk.ALIGN_CENTER);
                documento.open();
                PdfPTable tabla1 = new PdfPTable(1);
                PdfPTable tabla7 = new PdfPTable(2);
                PdfPTable tabla2 = new PdfPTable(3);
                PdfPTable tabla3 = new PdfPTable(3);
                PdfPTable tabla4 = new PdfPTable(1);
                PdfPTable tabla5 = new PdfPTable(2);
                PdfPTable tabla6 = new PdfPTable(1);
                tabla1.addCell("Folio:");
                tabla7.addCell("Nombre:");
                tabla7.addCell("Telefono:");
                tabla2.addCell("Equipo:");
                tabla2.addCell("Marca:");
                tabla2.addCell("Modelo:");
                tabla3.addCell("SN:");
                tabla3.addCell("Eliminador:");
                tabla3.addCell("Contraseña:");
                tabla4.addCell("Notas:");
                tabla5.addCell("Empleado:");
                tabla5.addCell("Fecha:");
                tabla6.addCell("Diagnostico:");
                
                String sql = "SELECT * FROM sist WHERE FOLIO = (SELECT MAX(FOLIO) FROM sist)";
                try{
                    Statement sentencia=reg.createStatement();
                    ResultSet rs= sentencia.executeQuery(sql);
                    while(rs.next()){
                        tabla1.addCell(rs.getString(1));
                        tabla7.addCell(rs.getString(2));
                        tabla7.addCell(rs.getString(3));
                        tabla2.addCell(rs.getString(4));
                        tabla2.addCell(rs.getString(5));
                        tabla2.addCell(rs.getString(6));
                        tabla3.addCell(rs.getString(7));
                        tabla3.addCell(rs.getString(8));
                        tabla3.addCell(rs.getString(9));
                        tabla4.addCell(rs.getString(10));
                        tabla5.addCell(rs.getString(11));
                        tabla5.addCell(rs.getString(12));
                        tabla6.addCell("\n"+"\n"+"\n");
                    }
                    documento.add(header);
                    documento.add(tabla1);
                    documento.add(tabla7);
                    documento.add(tabla2);
                    documento.add(tabla3);
                    documento.add(tabla4);
                    documento.add(tabla5);
                    documento.add(tabla6);
                    documento.add(firma);
                    documento.add(header);
                    documento.add(tabla1);
                    documento.add(tabla7);
                    documento.add(tabla2);
                    documento.add(tabla3);
                    documento.add(tabla4);
                    documento.add(tabla5);
                    //documento.add(tabla6);
                }catch(DocumentException | SQLException ex){
                    JOptionPane.showMessageDialog(null,"Ha ocurrido un error:(\n "+ex);
                    Logger.getLogger(addmin.class.getName()).log(Level.SEVERE, null, ex);
                }
                documento.close();
                JOptionPane.showMessageDialog(null,"Documento generado correctamente:)");
            }catch(DocumentException | HeadlessException | FileNotFoundException ex){
                JOptionPane.showMessageDialog(null,"Ha ocurrido un error:(\n"+ex);
                Logger.getLogger(addmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(addmin.class.getName()).log(Level.SEVERE, null, ex);
            }
            limpiar();
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
